Logging: 
  IncludeScopes: false
  LogLevel: 
    Default: Information
    System: Information
    Microsoft: Information
eureka:
  client: 
    serviceUrl: http://localhost:8761/eureka/
    validate_certificates: false
