Logging: 
  IncludeScopes: false
  Debug:
    LogLevel: 
      Default: Information
  Console:
    DisableColors: true
    LogLevel: 
      Default: Information
eureka:
  client: 
    serviceUrl: http://localhost:8761/eureka/
    validate_certificates: false
security:
  oauth2:
    client:
      validate_certificates: false    
management: 
  endpoints: 
    path: /cloudfoundryapplication
    cloudfoundry: 
      validateCertificates: false
  metrics:
    exporter:
      cloudfoundry:
        validateCertificates: false
  tracing:
    alwaysSample: true
    egressIgnorePattern: /api/v2/spans|/v2/apps/.*/permissions|/eureka/.*|/oauth/.*
    useShortTraceIds: true
    exporter
      zipkin:
        endpoint: http://localhost:9411/api/v2/spans
        validateCertificates: false
        useShortTraceIds: true
